services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: stockpilot
      POSTGRES_USER: stockpilot_user
      POSTGRES_PASSWORD: stockpilot_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
